name: Docker Image and Deployment CI

on:
  workflow_dispatch:
    inputs:
      only_env:
        description: "Only update .env"
        type: boolean
        required: false
        default: false
  push:
    branches:
      - main
      - develop

jobs:

  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        if: inputs.only_env == false
        run: sudo docker build . --tag excali-front-dev:latest -f Dockerfile

      - name: Run Docker image
        working-directory: ${{ secrets.DESTINATION_PATH }}
        run: docker compose up -d
